### PR TITLE
feat: Update container base image

### PR DESCRIPTION
**Pull request by raelga**
- Replace base image with distroless/static: smaller and less prone to vulnerabilities
- Enables using a non-docker container engine for building using the CONTAINER_ENGINE env var
- Adds the OWNERs file for enabling Prow tide and approval plugins

/kind feature
/priority important-longterm
/assign

### CODE REVIEW

**Review by roivaz — APPROVED** [review]

**Comment by raelga** [comment]
PR manually merged as the OWNERs file it's going to be included with this PR.

**Pull request merged**
